<?xml version="1.0"?>
<robot name="mybot" xmlns:xacro="http://www.ros.org/wiki/xacro">
        <!-- Put here the robot description -->
	<xacro:property name="PI" value="3.1415926535897931"/>

	<xacro:property name="chassisHeight" value="0.314"/>
	<xacro:property name="chassisLength" value="0.42834"/>
	<xacro:property name="chassisWidth" value="0.2"/>
	<xacro:property name="chassisMass" value="50"/>

	<xacro:property name="casterRadius" value="0.05"/>
	<xacro:property name="casterMass" value="5"/>

	<xacro:property name="wheelWidth" value="0.06"/>
	<xacro:property name="wheelRadius" value="0.1"/>
	<xacro:property name="wheelPos" value="0.15"/>
	<xacro:property name="wheelMass" value="5"/>

	<xacro:property name="cameraSize" value="0.05"/>
	<xacro:property name="cameraMass" value="0.1"/>

	<xacro:property name="laserSize" value="0.01"/>
	<xacro:property name="laserMass" value="0.1"/>

	<xacro:include filename="$(find mybot_description)/urdf/mybot.gazebo" />
	<xacro:include filename="$(find mybot_description)/urdf/materials.xacro" />
	<xacro:include filename="$(find mybot_description)/urdf/macros.xacro" />

	<link name="footprint" />

	<joint name="base_joint" type="fixed">
	  <parent link="footprint"/>
	  <child link="chassis"/>
	</joint>

	<link name='chassis'>
	  <collision>
		<origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
		<geometry>
		  <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
		</geometry>
	  </collision>

	  <visual>
		<origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
		<geometry>
		  <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
		</geometry>
		<material name="orange"/>
	  </visual>

	  <inertial>
		<origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
		<mass value="${chassisMass}"/>
		<box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
	  </inertial>
	</link>

	<joint name="fixed" type="fixed">
	  <parent link="chassis"/>
	  <child link="caster_wheel"/>
	</joint>

	<link name="caster_wheel">
	  <collision>
		<origin xyz="${casterRadius-chassisLength/2} 0 -0.05" rpy="0 0 0"/>
		<geometry>
		  <sphere radius="${casterRadius}"/>
		</geometry>
	  </collision>

	  <visual>
			<origin xyz="${casterRadius-chassisLength/2} 0 -0.05" rpy="0 0 0"/>
			<geometry>
			  <sphere radius="${casterRadius}"/>
			</geometry>
			<material name="red"/>
	  </visual>

	  <inertial>
			<origin xyz="${casterRadius-chassisLength/2} 0 -0.05" rpy="0 0 0"/>
			<mass value="${casterMass}"/>
			<sphere_inertia m="${casterMass}" r="${casterRadius}"/>
	  </inertial>
	</link>

	<wheel lr="left_front" tX="1" tY="1"/>
	<wheel lr="right_front" tX="1" tY="-1"/>
	<wheel lr="left_back" tX="-1" tY="1"/>
	<wheel lr="right_back" tX="-1" tY="-1"/>

	<joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${0.03+chassisLength/2} 0 0.2" rpy="0 0.191 0"/>
    <parent link="chassis"/>
    <child link="camera"/>
  </joint>

	<link name="camera">
	  <collision>
	    <origin xyz="0 0 0" rpy="0 0 0"/>
	    <geometry>
	      <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
	    </geometry>
	  </collision>

	  <visual>
	    <origin xyz="0 0 0" rpy="0 0 0"/>
	    <geometry>
	      <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
	    </geometry>
	    <material name="blue"/>
	  </visual>

	  <inertial>
	    <mass value="${cameraMass}" />
	    <origin xyz="0 0 0" rpy="0 0 0"/>
	    <box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
	  </inertial>
	</link>

	<joint name="Laser_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${0.01+chassisLength/2} 0 -0.05" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="laser"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="laser">
		<collision>
	    <origin xyz="0 0 0" rpy="0 0 0"/>
	    <geometry>
	      <box size="${laserSize} ${laserSize} ${laserSize}"/>
	    </geometry>
	  </collision>

	  <visual>
	    <origin xyz="0 0 0" rpy="0 0 0"/>
	    <geometry>
	      <box size="${laserSize} ${laserSize} ${laserSize}"/>
	    </geometry>
	    <material name="yellow"/>
	  </visual>

	  <inertial>
	    <mass value="${laserMass}" />
	    <origin xyz="0 0 0" rpy="0 0 0"/>
	    <box_inertia m="${laserSize}" x="${laserSize}" y="${laserSize}" z="${laserSize}" />
	  </inertial>
  </link>

</robot>
